apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omni-router.fullname" . }}
  labels:
    {{- include "omni-router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "omni-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "omni-router.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omni-router.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OMNI_HOST
              value: {{ .Values.env.OMNI_HOST | quote }}
            - name: OMNI_PORT
              value: {{ .Values.env.OMNI_PORT | quote }}
            {{- range $key, $val := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "omni-router.fullname" $ }}
                  key: {{ $key }}
                  optional: true
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
