apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-router.fullname" . }}
  labels:
    {{- include "omni-router.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
